name: Ruff
on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/ruff.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/ruff.yml"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Use ruff twice for linting and formatting.
      # See https://github.com/astral-sh/ruff-action/issues/23#issuecomment-2525574730
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
